#!/bin/bash

echo "================================================"
echo "🚀 QUICK APK BUILD - Do This Right Now!"
echo "   Takes 2 minutes to start, 10 min to build"
echo "================================================"
echo ""

echo "Copy and paste these commands ONE BY ONE:"
echo ""
echo "────────────────────────────────────────────────"
echo ""
echo "# 1. Install EAS (if you don't have it)"
echo "npm install -g eas-cli"
echo ""
echo "# 2. Go to your project"
echo "cd /app/frontend"
echo ""
echo "# 3. Login to Expo (or create account at expo.dev)"
echo "eas login"
echo ""
echo "# 4. Build APK (this starts the cloud build)"
echo "eas build --platform android --profile preview --non-interactive"
echo ""
echo "────────────────────────────────────────────────"
echo ""
echo "After running those 4 commands:"
echo "1. Wait 10 minutes for build to finish"
echo "2. Download APK from the URL it gives you"
echo "3. I'll upload it to GitHub for you!"
echo ""
echo "OR send me your Expo username/password and I'll do it!"
echo ""
